### ISSUE TITLE
Func deploy command output masks function URL on deploy command

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#1138]
On func deploy command, the progress indicator (clock) does not disappear at the end so it masks a bit the actual function URL output

```
$ ./func deploy --path /tmp/func-node-http --registry image-registry.openshift-image-registry.svc:5000/functest
   🙌 Function image built: image-registry.openshift-image-registry.svc:5000/functest/func-node-http:latest
   Function deployed in namespace "functest" and exposed at URL: 
🕑 ps://func-node-http-functest.apps.jeramos.mycluster.dev.net
$
```
I think the URL should be fully displayed. i.e `https://func-node-http-functest.apps.jeramos.mycluster.dev.net`

**Comment by lance** [comment]
@jrangelramos I think that the PR which merged last week should resolve this. Can you confirm with a local build? https://github.com/knative-sandbox/kn-plugin-func/pull/1133

**Comment by jrangelramos** [comment]
Hi @lance . Yes I tried a fresh clone + build in a fresh linux vm, and it still persist.

**Comment by matejvasek** [comment]
It works for me @jrangelramos .

**Comment by matejvasek** [comment]
@lance you fixed credentials overwrite, not url overwrite.
